apiVersion: apps/v1
kind: Deployment
metadata:
  name: photovault-fe
  namespace: webapps
  labels:
    app: photovault-fe
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: photovault-fe
  template:
    metadata:
      labels:
        app: photovault-fe
        component: frontend
      annotations:
        # This annotation will be updated by the CI/CD pipeline to force pod recreation
        deployment.kubernetes.io/revision: "1"
    spec:
      containers:
      - name: photovault-fe
        image: ghcr.io/ekskog/photovault-fe:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        # API Configuration
        - name: VITE_API_URL
          value: "https://vault-api.hbvu.su"
        # Authentication Mode: demo for development, api for production
        - name: VITE_AUTH_MODE
          value: "demo"
        # Debug Configuration
        - name: VITE_DEBUG
          value: "false"  # Set to "true" or "hbvu:*" to enable debug logging
        - name: VITE_DEBUG_PATTERN
          value: "hbvu:*"  # Debug pattern when debugging is enabled
        # Load non-sensitive config from ConfigMap
        envFrom:
        - configMapRef:
            name: photovault-frontend-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            httpHeaders:
            - name: User-Agent
              value: "k8s-healthcheck"
          initialDelaySeconds: 30
          periodSeconds: 300
          timeoutSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            httpHeaders:
            - name: User-Agent
              value: "k8s-healthcheck"
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
      imagePullSecrets:
      - name: ghcr-secret
      restartPolicy: Always
