apiVersion: apps/v1
kind: Deployment
metadata:
  name: photovault-frontend
  namespace: webapps
  labels:
    app: photovault-frontend
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photovault-frontend
  template:
    metadata:
      labels:
        app: photovault-frontend
        component: frontend
    spec:
      containers:
      - name: photovault-frontend
        image: ghcr.io/ekskog/photovault-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
