apiVersion: apps/v1
kind: Deployment
metadata:
  name: photovault-vue
  namespace: webapps
  labels:
    app: photovault-vue
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photovault-vue
  template:
    metadata:
      labels:
        app: photovault-vue
        component: frontend
    spec:
      containers:
      - name: photovault-vue
        image: ghcr.io/ekskog/photovault-vue:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            httpHeaders:
            - name: User-Agent
              value: "k8s-healthcheck"
          initialDelaySeconds: 30
          periodSeconds: 300
          timeoutSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            httpHeaders:
            - name: User-Agent
              value: "k8s-healthcheck"
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always
