apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: webapps
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiZWtza29nIiwKICAgICAgInBhc3N3b3JkIjogIllPVVJfR0lUSFVCX1BBVCIsCiAgICAgICJhdXRoIjogIllPVVJfQkFTRTY0X0FOQ09ERURfVVNFUk5BTUVfQU5EX1BBVCIKICAgIH0KICB9Cn0=
---
# Instructions for creating the secret:
# 1. Replace YOUR_GITHUB_PAT with your actual GitHub Personal Access Token
# 2. Replace YOUR_BASE64_ENCODED_USERNAME_AND_PAT with base64 encoded "username:pat"
# 3. To encode: echo -n "ekskog:YOUR_GITHUB_PAT" | base64
#
# Alternative method using kubectl:
# kubectl create secret docker-registry ghcr-secret \
#   --docker-server=ghcr.io \
#   --docker-username=ekskog \
#   --docker-password=YOUR_GITHUB_PAT \
#   --namespace=webapps
