apiVersion: v1
kind: Secret
metadata:
  name: photovault-frontend-secrets
  namespace: webapps
  labels:
    app: photovault-vue
    component: frontend
type: Opaque
data:
  # Base64 encoded values - replace with your actual production values
  # To encode: echo -n "your-value" | base64
  
  # API Configuration
  VITE_API_URL: aHR0cHM6Ly92YXVsdC1hcGkuaGJ2dS5zdQ==  # https://vault-api.hbvu.su
  
  # Production Mode (disable demo)
  VITE_DEMO_MODE: ZmFsc2U=  # false
  
  # Backend Authentication Endpoints
  VITE_AUTH_ENDPOINT: L2FwaS9hdXRoL2xvZ2lu  # /api/auth/login
  VITE_USER_ENDPOINT: L2FwaS91c2Vycw==      # /api/users
  
  # JWT Configuration (if needed)
  VITE_JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl  # your-jwt-secret-key-here
  
  # Optional: Additional security settings
  VITE_SESSION_TIMEOUT: ODY0MDA=  # 86400 (24 hours in seconds)
  VITE_API_TIMEOUT: MzAwMDA=      # 30000 (30 seconds in milliseconds)

---
# Development/Staging Secret (optional - for non-production environments)
apiVersion: v1
kind: Secret  
metadata:
  name: photovault-frontend-dev-secrets
  namespace: webapps
  labels:
    app: photovault-vue
    component: frontend
    environment: development
type: Opaque
data:
  # Development configuration with demo mode enabled
  VITE_API_URL: aHR0cHM6Ly92YXVsdC1hcGkuaGJ2dS5zdQ==
  VITE_DEMO_MODE: dHJ1ZQ==
  VITE_DEMO_ADMIN_USERNAME: YWRtaW4=
  VITE_DEMO_ADMIN_PASSWORD: YWRtaW4xMjM=
  VITE_DEMO_USER_USERNAME: dXNlcg==
  VITE_DEMO_USER_PASSWORD: dXNlcjEyMw==
