apiVersion: v1
kind: Service
metadata:
  name: photovault-vue-service
  namespace: webapps
  labels:
    app: photovault-vue
    component: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: photovault-vue
