apiVersion: v1
kind: Service
metadata:
  name: photovault-fe-service
  namespace: webapps
  labels:
    app: photovault-fe
    component: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.206
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: photovault-fe
    