name: Build and Deploy to K8s

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.EK_GITHUB_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}
            ghcr.io/${{ github.repository }}:latest

  apply-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode KUBECONFIG and set up file
        run: |
          echo "${{ secrets.kubecONFIG }}" | base64 --decode > kubeconfig
          chmod 600 kubeconfig

      - name: Apply manifests
        run: kubectl --kubeconfig=kubeconfig apply -f k8s/
