name: Build and Deploy PhotoVault Frontend

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/ekskog/photovault-vue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'
        
    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config
        
    - name: Verify cluster connection
      run: |
        kubectl cluster-info
        kubectl get nodes
        
    - name: Deploy to Kubernetes
      run: |
        # Apply manifests first (create if doesn't exist)
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        
        # Update image in deployment
        kubectl set image deployment/photovault-vue photovault-vue=${{ env.IMAGE_NAME }}:latest -n webapps
        
        # Wait for rollout to complete
        kubectl rollout status deployment/photovault-vue -n webapps --timeout=300s
        
    - name: Get service status
      run: |
        echo "=== Deployment Status ==="
        kubectl get deployment photovault-vue -n webapps
        echo ""
        echo "=== Pods ==="
        kubectl get pods -l app=photovault-vue -n webapps
        echo ""
        echo "=== Service ==="
        kubectl get service photovault-vue-service -n webapps
        echo ""
        echo "=== External IP (MetalLB) ==="
        kubectl get service photovault-vue-service -n webapps -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
