name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - 'nginx.conf'
      - 'vite.config.js'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: ghcr.io/ekskog/photovault-fe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for source code changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            source:
              - src/**
              - public/**
              - package.json
              - package-lock.json
              - Dockerfile
              - nginx.conf
              - vite.config.js

      - name: Set Environment Variables
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "IMAGE_TAG=${{ env.IMAGE_NAME }}:pr-${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ env.IMAGE_NAME }}:$SHORT_SHA" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        if: steps.changes.outputs.source == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.EK_GITHUB_PAT }}

      - name: Build and Push Docker Image
        if: steps.changes.outputs.source == 'true'
        run: |
          echo "Building and pushing image: $IMAGE_TAG"
          docker buildx build --platform linux/amd64 -t $IMAGE_TAG -t ${{ env.IMAGE_NAME }}:latest --push .
      
      - name: Skip Build (No Source Changes)
        if: steps.changes.outputs.source != 'true'
        run: |
          echo "No source code changes detected. Skipping Docker build."
          echo "Using existing image tag for deployment: $IMAGE_TAG"
      
      - name: Set Up KUBECONFIG
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          echo "KUBECONFIG set to $KUBECONFIG"
                    
      - name: Deploy to Kubernetes
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && steps.changes.outputs.source == 'true'
        run: |
          echo "Deploying image: $IMAGE_TAG"
          kubectl set image deployment/photovault-vue photovault-vue=$IMAGE_TAG --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml
          
          # Add debugging information
          echo "Checking deployment status..."
          kubectl get deployment photovault-vue --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml
          
          echo "Checking pod status..."
          kubectl get pods -l app=photovault-vue --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml
          
          echo "Checking recent events..."
          kubectl get events --namespace=webapps --sort-by='.lastTimestamp' --kubeconfig=$PWD/kubeconfig.yaml | grep -E "(Pull|Image|Failed|Error)" | tail -10
          
          # Wait for rollout with detailed output
          kubectl rollout status deployment/photovault-vue --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml --timeout=600s

      - name: Skip Deployment (No Source Changes)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && steps.changes.outputs.source != 'true'
        run: |
          echo "No source code changes detected. Skipping Kubernetes deployment."
          echo "Existing deployment will continue running with the current image."

      - name: Get Service Info
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && steps.changes.outputs.source == 'true'
        run: |
          echo "Service information:"
          kubectl get service photovault-vue-service --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml -o wide
          
          echo "External IP (if available):"
          kubectl get service photovault-vue-service --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml -o jsonpath='{.status.loadBalancer.ingress[0].ip}'

      - name: Debug on Failure
        if: failure()
        run: |
          echo "Deployment failed. Gathering debug information..."
          kubectl describe deployment photovault-vue --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml
          kubectl describe pods -l app=photovault-vue --namespace=webapps --kubeconfig=$PWD/kubeconfig.yaml
